src/Entity/Game.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: "App\Repository\GameRepository")]
class Game
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\Column(type: "string", length: 200)]
    private $url;

    #[ORM\Column(type: "integer")]
    private $increment;

    #[ORM\Column(type: "string", length: 255)]
    private $fen;

    #[ORM\Column(nullable: true)]
    private ?float $time = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_insert = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Moves::class, orphanRemoval: true)]
    private Collection $moves;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column(length: 5, nullable: true)]
    private ?string $winner = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $end_reason = null;

    #[ORM\OneToMany(mappedBy: 'game', targetEntity: Messages::class, orphanRemoval: true)]
    private Collection $messages;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $pgn = null;

    #[ORM\Column(length: 100)]
    private ?string $type = null;

    #[ORM\Column(length: 20)]
    private ?string $creator_color_chose = null;

    #[ORM\Column(nullable: true)]
    private ?int $ai_level = null;

    public function __construct()
    {
        $this->moves = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getIncrement(): ?int
    {
        return $this->increment;
    }

    public function setIncrement(int $increment): self
    {
        $this->increment = $increment;

        return $this;
    }

    public function getFen(): ?string
    {
        return $this->fen;
    }

    public function setFen(string $fen): self
    {
        $this->fen = $fen;

        return $this;
    }

    public function getTime(): ?float
    {
        return $this->time;
    }

    public function setTime(?float $time): static
    {
        $this->time = $time;

        return $this;
    }

    public function getDateInsert(): ?\DateTimeInterface
    {
        return $this->date_insert;
    }

    public function setDateInsert(\DateTimeInterface $date_insert): static
    {
        $this->date_insert = $date_insert;

        return $this;
    }

    /**
     * @return Collection<int, Moves>
     */
    public function getMoves(): Collection
    {
        return $this->moves;
    }

    public function addMove(Moves $move): static
    {
        if (!$this->moves->contains($move)) {
            $this->moves->add($move);
            $move->setGame($this);
        }

        return $this;
    }

    public function removeMove(Moves $move): static
    {
        if ($this->moves->removeElement($move)) {
            // set the owning side to null (unless already changed)
            if ($move->getGame() === $this) {
                $move->setGame(null);
            }
        }

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getWinner(): ?string
    {
        return $this->winner;
    }

    public function setWinner(?string $winner): static
    {
        $this->winner = $winner;

        return $this;
    }

    public function getEndReason(): ?string
    {
        return $this->end_reason;
    }

    public function setEndReason(?string $end_reason): static
    {
        $this->end_reason = $end_reason;

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setGame($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getGame() === $this) {
                $message->setGame(null);
            }
        }

        return $this;
    }

    public function getPgn(): ?string
    {
        return $this->pgn;
    }

    public function setPgn(?string $pgn): static
    {
        $this->pgn = $pgn;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCreatorColorChose(): ?string
    {
        return $this->creator_color_chose;
    }

    public function setCreatorColorChose(string $creator_color_chose): static
    {
        $this->creator_color_chose = $creator_color_chose;

        return $this;
    }

    public function getAiLevel(): ?int
    {
        return $this->ai_level;
    }

    public function setAiLevel(?int $ai_level): static
    {
        $this->ai_level = $ai_level;

        return $this;
    }
}

templates/profile/account.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.request.host }} | Mon compte{% endblock %}

{% block style_container %}margin: 32px auto;{% endblock %}

{% block stylesheets %}
    <style>
        .feature-icon-small {
            width: 3rem;
            height: 3rem;
        }
    </style>
{% endblock %}

{% block body %}
    <h1 class="visually-hidden">Votre compte client {{ app.request.host }}</h1>

    <div class="container px-4 py-5">
        <h2 class="pb-2 border-bottom">Bienvenue dans votre espace joueur sur {{ app.request.host }} !</h2>

        <div class="row row-cols-1 row-cols-md-2 align-items-md-center g-5 py-5">
            <div class="col d-flex flex-column align-items-start gap-2">
                <h2 class="fw-bold text-body-emphasis">Explorez vos statistiques et améliorez votre jeu.</h2>
                <p class="text-body-secondary">Consultez vos parties, vos statistiques, vos informations personnelles et découvrez des astuces pour progresser. Votre espace est conçu pour vous aider à devenir un meilleur joueur.</p>
                <a href="{{ path('logout') }}" class="btn btn-primary btn-lg">Déconnexion</a>
            </div>

            <div class="col">
                <div class="row row-cols-1 row-cols-sm-2 g-4">
                    <a href="{{ path('profileInfoPerso') }}" class="text-decoration-none" title="Informations personnelles">
                        <div class="col d-flex flex-column gap-2">
                            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                                <i class="bi bi-person-circle"></i>
                            </div>
                            <h4 class="fw-semibold mb-0 text-body-emphasis">Informations personnelles</h4>
                            <p class="text-body-secondary mb-0">Modifiez votre adresse email, mot de passe et pseudo.</p>
                            <div class="icon-link icon-link-hover">
                                Continuer <i class="bi bi-chevron-right" style="line-height: 1;"></i>
                            </div>
                        </div>
                    </a>

                    <a href="{{ path('profileGameHistory') }}" class="text-decoration-none" title="Historique des parties">
                        <div class="col d-flex flex-column gap-2">
                            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                                <i class="bi bi-clock-history"></i>
                            </div>
                            <h4 class="fw-semibold mb-0 text-body-emphasis">Historique des parties</h4>
                            <p class="text-body-secondary mb-0">Regardez et revisionnez l'historique de vos parties d'échecs.</p>
                            <div class="icon-link icon-link-hover">
                                Continuer <i class="bi bi-chevron-right" style="line-height: 1;"></i>
                            </div>
                        </div>
                    </a>

                    <a href="" class="text-decoration-none" title="Statistiques">
                        <div class="col d-flex flex-column gap-2">
                            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                                <i class="bi bi-bar-chart-line"></i>
                            </div>
                            <h4 class="fw-semibold mb-0 text-body-emphasis">Statistiques</h4>
                            <p class="text-body-secondary mb-0">Consultez vos statistiques.</p>
                            <div class="icon-link icon-link-hover">
                                Continuer <i class="bi bi-chevron-right" style="line-height: 1;"></i>
                            </div>
                        </div>
                    </a>

                    <a href="" class="text-decoration-none" title="Messagerie">
                        <div class="col d-flex flex-column gap-2">
                            <div class="feature-icon-small d-inline-flex align-items-center justify-content-center text-bg-primary bg-gradient fs-4 rounded-3">
                                <i class="bi bi-chat-dots"></i>
                            </div>
                            <h4 class="fw-semibold mb-0 text-body-emphasis">Messagerie</h4>
                            <p class="text-body-secondary mb-0">Consultez votre messagerie et invitez des amis.</p>
                            <div class="icon-link icon-link-hover">
                                Continuer <i class="bi bi-chevron-right" style="line-height: 1;"></i>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/profile/games-history.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.request.host }} | Mon compte - Historique des parties{% endblock %}

{% block style_container %}max-width:968px; margin: 32px auto;{% endblock %}

{% block javascripts %}
    <script>
        const PIECESIMGURL = "{{ asset('assets/img/pieces/playerColor-chessboard.png') }}";
        let GAMESLIST = [];
        {% for oneGame in gamePlayers %}
            GAMESLIST.push({
                'id': '{{ oneGame.game.id }}',
                'fen': '{{ oneGame.game.fen }}',
                'pgn': '{{ oneGame.game.pgn }}',
            })
        {% endfor %}
        // EOF fill the show chessboard
    </script>

    {{ encore_entry_link_tags('gameHistoryJs') }}
{% endblock %}

{% block stylesheets %}
    <style>
        .height240 {
            height: 15rem;
        }
    </style>
    {{ encore_entry_script_tags('gameHistoryJs') }}
{% endblock %}

{% block body %}
    <div class="mb-4">
        <a href="{{ path('profile') }}" class="no-decoration" title="Mon compte">
            Mon compte <i class="bi bi-chevron-right" style="line-height: 1;"></i>
        </a>
    </div>

    <div class="text-center mb-5">
        <h1>Historique des parties</h1>
    </div>

    <div class="row">
        {% for oneGame in gamePlayers %}
            {% set gameUrl = path('game', {'url': oneGame.game.url}) %}
            {% if oneGame.game.type == 'against-ai' %}
                {% set gameUrl = path('gameAi', {'url': oneGame.game.url}) %}
            {% endif %}

            <a href="{{ gameUrl }}" class="col-12 mb-4 no-decoration">
                <div class="row height240">
                    <div class="col-4 game-history-board">
                        <div class="board-account-history">
                            {% if oneGame.color == 'w' %}
                                {% for key, column in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] %}
                                    <div class="one-column">
                                        {% for line in 8..1 %}
                                            {% if key is even %}
                                                <div id="{{ oneGame.game.id ~ '-' ~ column ~ line }}" class="chess-table {{ line is even ? 'case-white' : 'case-black' }}">
                                                </div>
                                            {% else %}
                                                <div id="{{ oneGame.game.id ~ '-' ~ column ~ line }}" class="chess-table {{ line is even ? 'case-black' : 'case-white' }}">
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                            {% else %}
                                {% for key, column in ['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'] %}
                                    <div class="one-column">
                                        {% for line in 1..8 %}
                                            {% if key is even %}
                                                <div id="{{ oneGame.game.id ~ '-' ~ column ~ line }}" class="chess-table {{ line is even ? 'case-white' : 'case-black' }}">
                                                </div>
                                            {% else %}
                                                <div id="{{ oneGame.game.id ~ '-' ~ column ~ line }}" class="chess-table {{ line is even ? 'case-black' : 'case-white' }}">
                                                </div>
                                            {% endif %}
                                        {% endfor %}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-md-8 col-12 bg-body-tertiary border rounded-3 d-flex flex-column justify-content-between">
                        {% set timeDisplay = '∞' %}
                        {% if oneGame.game.time is not null %}
                            {% set timeDisplay = oneGame.game.time / 60 ~ ' + ' ~ oneGame.game.increment %}
                        {% endif %}

                        <div>
                            <h2 class="mb-0">{{ timeDisplay }} | {{ game_type[oneGame.game.type] }}</h2>
                            <p class="mb-0">{{ oneGame.game.dateInsert|date('d/m/Y H:i:s') }}</p>
                        </div>

                        <div class="text-center">
                            {% if oneGame.game.status == 'finished' %}
                                {% if oneGame.game.winner == 'd' %} {# draw #}
                                    {% if oneGame.game.endReason == 'playersAgreement' %}
                                        <p>Match nul par accord mutuel</p>
                                    {% elseif oneGame.game.endReason == 'stalemate' %}
                                        <p>Match nul : jeu bloqué</p>
                                    {% elseif oneGame.game.endReason == 'threefoldRepetition' %}
                                        <p>Match nul : 3 déplacements consécutifs</p>
                                    {% elseif oneGame.game.endReason == 'insufficientMaterial' %}
                                        <p>Match nul : nombre de pièces insuffisantes</p>
                                    {% elseif oneGame.game.endReason == 'fiftyMoves' %}
                                        <p>Match nul : 50 coups joués sans progrès</p>
                                    {% endif %}
                                {% else %} {# winner #}
                                    {% set reason = 'Échec et mat' %}
                                    {% if oneGame.game.endReason == 'timeout' %}
                                        {% set reason = 'Temps écoulé' %}
                                    {% elseif oneGame.game.endReason == 'resign' %}
                                        {% set reason = 'Abandon' %}
                                    {% endif %}

                                    {% if oneGame.color == 'w' and oneGame.game.winner == 'w' %} {# victory while playing white #}
                                        <p class="text-success">Victoire des Blancs : {{ reason }}</p>
                                    {% elseif oneGame.color == 'b' and oneGame.game.winner == 'b' %} {# victory while playing black #}
                                        <p class="text-success">Victoire des Noirs : {{ reason }}</p>
                                    {% elseif oneGame.color == 'w' and oneGame.game.winner == 'b' %} {# lose while playing white #}
                                        <p class="text-danger">Victoire des Noirs : {{ reason }}</p>
                                    {% else %} {# lose while playing black #}
                                        <p class="text-danger">Victoire des Blancs : {{ reason }}</p>
                                    {% endif %}
                                {% endif %}
                            {% else %}
                                <p>{{ game_status[oneGame.game.status] }}</p>
                            {% endif %}
                        </div>

                        <div>
                            {% if ' 4. ' in oneGame.game.pgn %}
                                {% set pgnSplited = oneGame.game.pgn|split(' 4. ') %}
                                {% set fenSplited = oneGame.game.fen|split(' ') %}

                                <p class="mb-0">{{ pgnSplited[0] }} ... {{ fenSplited[5] }} moves</p>
                            {% else %}
                                <p class="mb-0">{{ oneGame.game.pgn }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </a>
        {% else %}
            <div class="alert alert-info d-flex align-items-center" role="alert">
                <i class="bi bi-info-circle me-2" style="font-size:1.5rem"></i>
                <div>
                    Aucunes parties jouées
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/profile/infos-perso.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.request.host }} | Mon compte - Informations personnelles{% endblock %}

{% block style_container %}max-width:968px; margin: 32px auto;{% endblock %}

{% block body %}
    <div class="mb-4">
        <a href="{{ path('profile') }}" class="no-decoration" title="Mon compte">
            Mon compte <i class="bi bi-chevron-right" style="line-height: 1;"></i>
        </a>
    </div>
    {% if status == 'infos-edited' %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <i class="bi bi-check-circle-fill me-2" style="font-size:1.5rem"></i>
            <div>
                Vos informations ont été modifiés
            </div>
        </div>
    {% endif %}

    {% if status == 'password-edited' %}
        <div class="alert alert-success d-flex align-items-center" role="alert">
            <i class="bi bi-check-circle-fill me-2" style="font-size:1.5rem"></i>
            <div>
                Votre mot de passe a été modifié
            </div>
        </div>
    {% endif %}

    {% if status == 'error-current-password' %}
        <div class="alert alert-danger d-flex align-items-center" role="alert">
            <i class="bi bi-x-circle-fill me-2" style="font-size:1.5rem"></i>
            <div>
                Votre mot de passe actuel est incorrect
            </div>
        </div>
    {% endif %}

    <div class="text-center mb-5">
        <h1>Informations personnelles</h1>
    </div>
    <div class="row">
        <div class="col-12 col-md-6">
            <h2>Mes informations</h2>
            {{ form(formPersonalInformations) }}
        </div>
        <div class="col-12 col-md-6">
            <h2>Mon mot de passe</h2>
            {{ form(formPasswordEdit) }}
        </div>
    </div>
{% endblock %}