src/Entity/Challenge.php
<?php

namespace App\Entity;

use App\Repository\ChallengeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ChallengeRepository::class)]
class Challenge
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $ordering = null;

    #[ORM\Column]
    private ?int $score_goal = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    /**
     * @var Collection<int, ChallengeUser>
     */
    #[ORM\OneToMany(targetEntity: ChallengeUser::class, mappedBy: 'challenge', orphanRemoval: true)]
    private Collection $challengeUsers;

    #[ORM\Column(length: 255)]
    private ?string $fen = null;

    #[ORM\ManyToOne(inversedBy: 'challenges')]
    private ?ChallengeCategory $challengeCategory = null;

    public function __construct()
    {
        $this->challengeUsers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrdering(): ?int
    {
        return $this->ordering;
    }

    public function setOrdering(int $ordering): static
    {
        $this->ordering = $ordering;

        return $this;
    }

    public function getScoreGoal(): ?int
    {
        return $this->score_goal;
    }

    public function setScoreGoal(int $score_goal): static
    {
        $this->score_goal = $score_goal;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection<int, ChallengeUser>
     */
    public function getChallengeUsers(): Collection
    {
        return $this->challengeUsers;
    }

    public function addChallengeUser(ChallengeUser $challengeUser): static
    {
        if (!$this->challengeUsers->contains($challengeUser)) {
            $this->challengeUsers->add($challengeUser);
            $challengeUser->setChallenge($this);
        }

        return $this;
    }

    public function removeChallengeUser(ChallengeUser $challengeUser): static
    {
        if ($this->challengeUsers->removeElement($challengeUser)) {
            // set the owning side to null (unless already changed)
            if ($challengeUser->getChallenge() === $this) {
                $challengeUser->setChallenge(null);
            }
        }

        return $this;
    }

    public function getFen(): ?string
    {
        return $this->fen;
    }

    public function setFen(string $fen): static
    {
        $this->fen = $fen;

        return $this;
    }

    public function getChallengeCategory(): ?ChallengeCategory
    {
        return $this->challengeCategory;
    }

    public function setChallengeCategory(?ChallengeCategory $challengeCategory): static
    {
        $this->challengeCategory = $challengeCategory;

        return $this;
    }
}

src/Entity/Player.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: "App\Repository\PlayerRepository")]
class Player
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: "integer")]
    private $id;

    #[ORM\Column(type: "string", length: 20)]
    private $color;

    #[ORM\ManyToOne(targetEntity: "App\Entity\Game")]
    #[ORM\JoinColumn(nullable: false)]
    private $game;

    #[ORM\Column(type: "boolean")]
    private $game_creator;

    #[ORM\Column(type: "integer", nullable: true)]
    private $time_left;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Moves::class, orphanRemoval: true)]
    private Collection $moves;

    #[ORM\OneToMany(mappedBy: 'player', targetEntity: Messages::class)]
    private Collection $messages;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $user_agent = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $ip = null;

    #[ORM\ManyToOne(inversedBy: 'players')]
    private ?User $user = null;

    public function __construct()
    {
        $this->moves = new ArrayCollection();
        $this->messages = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getIdGame(): ?game
    {
        return $this->game;
    }

    public function setIdGame(?game $game): self
    {
        $this->game = $game;

        return $this;
    }

    public function getGameCreator(): ?bool
    {
        return $this->game_creator;
    }

    public function setGameCreator(bool $game_creator): self
    {
        $this->game_creator = $game_creator;

        return $this;
    }

    public function getTimeLeft(): ?int
    {
        return $this->time_left;
    }

    public function setTimeLeft(?int $time_left): self
    {
        $this->time_left = $time_left;

        return $this;
    }

    public function isGameCreator(): ?bool
    {
        return $this->game_creator;
    }

    public function getGame(): ?game
    {
        return $this->game;
    }

    public function setGame(?game $game): static
    {
        $this->game = $game;

        return $this;
    }

    /**
     * @return Collection<int, Moves>
     */
    public function getMoves(): Collection
    {
        return $this->moves;
    }

    public function addMove(Moves $move): static
    {
        if (!$this->moves->contains($move)) {
            $this->moves->add($move);
            $move->setPlayer($this);
        }

        return $this;
    }

    public function removeMove(Moves $move): static
    {
        if ($this->moves->removeElement($move)) {
            // set the owning side to null (unless already changed)
            if ($move->getPlayer() === $this) {
                $move->setPlayer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Messages>
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Messages $message): static
    {
        if (!$this->messages->contains($message)) {
            $this->messages->add($message);
            $message->setPlayer($this);
        }

        return $this;
    }

    public function removeMessage(Messages $message): static
    {
        if ($this->messages->removeElement($message)) {
            // set the owning side to null (unless already changed)
            if ($message->getPlayer() === $this) {
                $message->setPlayer(null);
            }
        }

        return $this;
    }

    public function getUserAgent(): ?string
    {
        return $this->user_agent;
    }

    public function setUserAgent(?string $user_agent): static
    {
        $this->user_agent = $user_agent;

        return $this;
    }

    public function getIp(): ?string
    {
        return $this->ip;
    }

    public function setIp(?string $ip): static
    {
        $this->ip = $ip;

        return $this;
    }

    public function getUser(): ?user
    {
        return $this->user;
    }

    public function setUser(?user $user): static
    {
        $this->user = $user;

        return $this;
    }
}

templates/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ app.request.host }} | À propos{% endblock %}

{% block body %}
    <div class="text-center">
        <h1>À propos de {{ app.request.host }}</h1>
    </div>
    <div class="row">
        <div class="col-12">
            <p>
                Bienvenue sur {{ app.request.host }}, une plateforme de jeu d'échecs gratuite, où stratégie et tactique se rencontrent pour une expérience de jeu captivante et stimulante. Ici, vous pouvez jouez avec un ami, contre un adversaire aléatoire et bientot contre un ordinateur de plusieurs niveaux.
            </p>

            <p>
                Je me présente en quelques mots. Je suis un développeur back-end avec plusieurs années d'expériences et je voulais faire un projet à la fois fun et techniquement challengeant pour améliorer continuellement mes compétences et me tenir à jour des technologies récentes que l'on a pas toujours le temps de voir en milieu professionnel. Le front n'étant pas mon point fort, ni mon domaine préféré, je m'excuse par avance pour le design minimaliste.
            </p>

            J'améliore continuellement ce site afin d'ajouter des fonctionnalités supplémentaires. Voici la roadmap :
            <ul>
                <li>Jouer contre l'ordinateur</li>
                <li>Section "Regarder" afin de pouvoir regarder les parties des autres joueurs en live</li>
                <li>Création du compte client afin d'enregistrer l'historique des parties des joueurs</li>
                <li>Création des "ranked" et d'un système de Elo</li>
            </ul>
            Lien vers mon <a target="_blank" href="https://github.com/raphael42/chessgame">github</a>
        </div>
    </div>
{% endblock %}

templates/base.html.twig
<!doctype html>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="Raphael Bellon">
        <meta name="robots" content="{% block meta_robots %}all{% endblock %}">

        <title id="title">{% block title %}{{ app.request.host }} | Jeu d'échecs gratuit{% endblock %}</title>

        <link rel="icon" type="image/png" href="{{ asset('assets/img/favicon-rook.png') }}">
        <link rel="canonical" href="{% block canonical %}{{ app.request.schemeAndHttpHost ~ app.request.pathInfo }}{% endblock %}">

        {% block stylesheets %}{% endblock %}
        {{ encore_entry_link_tags('allSite') }}
    </head>

    <body class="{% block body_class %}{% endblock %}">
        <header>
            {% include "menu.html.twig" %}
        </header>

        <div class="container-fluid mt-3" style="{% block style_container %}{% endblock %}">
            {% block body %}{% endblock %}
        </div>

        {% block javascripts %}{% endblock %}
        {{ encore_entry_script_tags('allSite') }}
    </body>
</html>

templates/learn-game.html.twig
{% extends 'base.html.twig' %}

{# {% block title %}{{ app.request.host }} | Apprendre les échecs{% endblock %} #}

{% block javascripts %}
    <script>
        const FEN = '{{ currentChallenge.fen }}';
        const PIECESIMGURL = "{{ asset('assets/img/pieces/playerColor-chessboard.png') }}";
        const AJAXSAVECHALLENGE = '{{ path('ajaxSaveChallenge') }}';
        {% if nextChallengeExist %}
            const NEXTCHALLENGEPATH = '{{ path('learnGame', {'gameCategory': currentChallenge.challengeCategory.slug, 'gameId': currentChallenge.ordering + 1}) }}';
        {% else %}
            const NEXTCHALLENGEPATH = null;
        {% endif %}
        const SLUG = '{{ currentChallenge.challengeCategory.slug }}';
        const ID = '{{ currentChallenge.ordering }}';
        const SCOREGOAL = '{{ currentChallenge.scoreGoal }}';
    </script>

    {{ encore_entry_link_tags('gameChallengesJs') }}
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_script_tags('gameChallengesJs') }}
{% endblock %}



{% block body %}
    <div class="row">
        <div class="col-lg-3 col-md-12 tchat-column">
            <section class="learn-menu-section">
                <a href="{{ path('learn') }}" class="section-title">Retour au menu</a>
                <div class="accordion" id="accordionLearnMenu">
                    <div class="accordion-item">
                        <h2 class="accordion-header" id="accordion-pieces">
                            <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#accordion-pieces-collapse" aria-expanded="true" aria-controls="accordion-pieces-collapse">
                                Les pièces
                            </button>
                        </h2>
                        <div id="accordion-pieces-collapse" class="accordion-collapse collapse show" aria-labelledby="accordion-pieces">
                            <div class="accordion-body">
                                <div class="list-group">
                                    {% for slug, listChallenges in challengesAdvancement %}
                                        {% set breakLoop = false %}
                                        {% for onechallenge in challenges %}
                                            {% if slug == onechallenge.challengeCategory.slug and not breakLoop %}
                                                {% set breakLoop = true %}
                                                {% if slug == currentChallenge.challengeCategory.slug %}
                                                    <a href="{{ path('learnGame', {'gameCategory': slug, 'gameId': challengeNumberLink[slug]}) }}" class="list-group-item list-group-item-action active" aria-current="true">{{ onechallenge.challengeCategory.title }}</a>
                                                {% else %}
                                                    <a href="{{ path('learnGame', {'gameCategory': slug, 'gameId': challengeNumberLink[slug]}) }}" class="list-group-item list-group-item-action">{{ onechallenge.challengeCategory.title }}</a>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                    {# <div class="accordion-item">
                        <h2 class="accordion-header" id="accordion-fondamentaux">
                            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#accordion-fondamentaux-collapse" aria-expanded="false" aria-controls="accordion-fondamentaux-collapse">
                                Les fondamentaux
                            </button>
                        </h2>
                        <div id="accordion-fondamentaux-collapse" class="accordion-collapse collapse" aria-labelledby="accordion-fondamentaux">
                            <div class="accordion-body">
                                <div class="list-group">
                                    {% for slug, listChallenges in challengesAdvancement %}
                                        {% set breakLoop = false %}
                                        {% for onechallenge in challenges %}
                                            {% if slug == onechallenge.slug and not breakLoop %}
                                                {% set breakLoop = true %}
                                                {% if slug == currentChallenge.slug %}
                                                    <a href="{{ path('learnGame', {'gameCategory': slug, 'gameId': 1}) }}" class="list-group-item list-group-item-action active" aria-current="true">{{ onechallenge.title }}</a>
                                                {% else %}
                                                    <a href="{{ path('learnGame', {'gameCategory': slug, 'gameId': 1}) }}" class="list-group-item list-group-item-action">{{ onechallenge.title }}</a>
                                                {% endif %}
                                            {% endif %}
                                        {% endfor %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div> #}
                </div>
            </section>
        </div>
        <div class="col-lg-9 col-md-12">
            <div class="row">
                <div class="col-md-8 col-12 board-column">
                    <div id="board">
                        {% for key, column in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] %}
                            <div class="one-column">
                                {% for line in 8..1 %}
                                    {% if key is even %}
                                        <div id="{{ column ~ line }}" class="chess-table {{ line is even ? 'case-white' : 'case-black' }}">
                                            {% if column == 'h' %}
                                                <span class="absolute-top-right">{{ line }}</span>
                                            {% endif %}

                                            {% if line == 1 %}
                                                <span class="absolute-bottom-left">{{ column }}</span>
                                            {% endif %}
                                        </div>
                                    {% else %}
                                        <div id="{{ column ~ line }}" class="chess-table {{ line is even ? 'case-black' : 'case-white' }}">
                                            {% if column == 'h' %}
                                                <span class="absolute-top-right">{{ line }}</span>
                                            {% endif %}

                                            {% if line == 1 %}
                                                <span class="absolute-bottom-left">{{ column }}</span>
                                            {% endif %}
                                        </div>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-4 col-12 d-flex flex-column flex-wrap justify-content-center">
                    {# TODO : display different levels #}
                    <section class="learn-advancement-section">
                        <div class="title bg-primary bg-gradient text-white ps-4">
                            <h2>{{ currentChallenge.challengeCategory.title }}</h2>
                            <p>{{ currentChallenge.challengeCategory.subtitle }}</p>
                        </div>
                        <div id="challenge-description" class="text-center mb-3">
                            {{ currentChallenge.description|raw }}
                        </div>
                        <div class="btn-toolbar justify-content-around" role="toolbar" aria-label="Toolbar with button groups">
                            <div class="btn-group w-100" role="group" aria-label="Btn group">
                                {% for slug, listChallenges in challengesAdvancement %}
                                    {% if slug == currentChallenge.challengeCategory.slug %}
                                        {% set widthBtn = 100 / listChallenges|length %}
                                        {% for oneChallengeOrdering, oneChallengeScore in listChallenges %}
                                            {% set btnClass = 'btn-outline-secondary' %}
                                            {% if currentChallenge.ordering == oneChallengeOrdering %}
                                                {% set btnClass = 'btn-primary' %}
                                            {% elseif oneChallengeScore is not null %}
                                                {% set btnClass = 'btn-success' %}
                                            {% endif %}

                                            <a class="btn {{ btnClass }} d-flex flex-wrap justify-content-center align-content-center px-1 py-1" style="width: {{ widthBtn }}%" href="{{ path('learnGame', {'gameCategory': slug, 'gameId': oneChallengeOrdering}) }}">
                                                {% if oneChallengeScore is not null %}
                                                    {% for i in 1..min(oneChallengeScore, 3) %}
                                                        <i class="bi bi-star-fill lh-1"></i>
                                                    {% endfor %}
                                                {% else %}
                                                    {{ oneChallengeOrdering }}
                                                {% endif %}
                                            </a>
                                        {% endfor %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>

    {% include 'modules/modals/promotion.html.twig' %}

    <div class="modal fade" id="final-modal" tabindex="-1" aria-labelledby="finalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Étape terminée</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="final-score">
                        {# TODO : display the score with the ajax request return datas ajaxSaveChallengeFunction #}
                    </div>
                    <p>Félicitations ! Vous maîtrisez ce niveau.</p>
                </div>
                <div class="modal-footer">
                    <a href="{{ path('learn') }}" class="btn btn-secondary">Retour au menu</a>
                    {% if nextChallengeCategory is not null %}
                        <a href="{{ path('learnGame', {'gameCategory': nextChallengeCategory, 'gameId': 1}) }}" class="btn btn-primary">Suivant</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/secondpage.html.twig
{% extends './base.html.twig' %}

{% block javascripts %}
    <script>
        const FEN = '{{ game.fen }}';
        const PGN = '{{ game.pgn }}';
        const INCREMENT = '{{ game.increment }}';
        const PLAYERCOLOR = '{{ player.color }}';
        const PLAYERTIMELEFT = '{{ player.timeLeft }}';
        const OPPONENTTIMELEFT = '{{ opponent.timeLeft }}';
        const IDGAME = '{{ game.id }}';
        const PIECESIMGURL = "{{ asset('assets/img/pieces/playerColor-chessboard.png') }}";
        var GAMESTATUS = {{ gameStatus|json_encode|raw }}; // This one can be updated in JS, so don't set up as const
        const PLAYERTYPE = '{{ playerType }}';
        const SERVERNAME = '{{ app.request.host }}';
    </script>

    {{ encore_entry_link_tags('gameJs') }}
{% endblock %}

{% block stylesheets %}
    {{ encore_entry_script_tags('gameJs') }}
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-12">
            {% if playerType == 'spectator' %}
                <div>
                    <p>Mode spectateur</p>
                </div>
            {% else %}
                <div class="row mb-3">
                    <div class="col-4">
                        <button id="takeback" class="btn btn-primary">
                            <i class="bi bi-skip-backward" title="Annuler le dernier déplacement"></i>
                        </button>
                    </div>

                    <div class="col-4">
                        <button id="offer-draw" class="btn btn-warning" title="Proposer une égalité">
                            ½
                        </button>
                    </div>

                    <div class="col-4">
                        <button id="resign" class="btn btn-danger" title="Abandonner">
                            <i class="bi bi-flag"></i>
                        </button>
                    </div>
                </div>
                <div class="row mb-3">
                    <div id="offer-draw-display" class="col-12 d-none">
                        <p>Proposition de match nul envoyé. En attente de réponse de votre adversaire</p>
                    </div>
                    <div id="offer-draw-opponent-response" class="col-12 d-none">
                        <p>Votre adversaire propose un match nul. Voulez-vous accepter ?</p>
                        <button id="offer-draw-yes" class="btn btn-success"><i class="bi bi-check-lg"></i> Oui</button>
                        <button id="offer-draw-no" class="btn btn-danger"><i class="bi bi-x-lg"></i>Non</button>
                    </div>

                    <div id="takeback-display" class="col-12 d-none">
                        <p>Proposition d'annulation envoyé à votre adversaire</p>
                    </div>
                    <div id="takeback-opponent-response" class="col-12 d-none">
                        <p>Demande d'annulation du dernier déplacement par votre adversaire. Voulez-vous accepter ?</p>
                        <button id="takeback-yes" class="btn btn-success"><i class="bi bi-check-lg"></i> Oui</button>
                        <button id="takeback-no" class="btn btn-danger"><i class="bi bi-x-lg"></i>Non</button>
                    </div>
                </div>
            {% endif %}
            <div class="tchat">
                {% for oneMessage in messages %}
                    <div>
                        {{ oneMessage.message }}
                    </div>
                {% endfor %}
            </div>
            <form id="form-tchat" class="{{ playerType == 'spectator' ? 'd-none' }}">
                <input id="input-tchat" type="text" class="form-control" placeholder="Écrire à votre adversaire">
            </form>
            <div class="spectators d-none">
                <p><i class="bi bi-person-fill"></i><span class="spectators-number"></span></p>
            </div>
        </div>
        <div class="col-lg-6 col-md-8 col-sm-12">
            <div id="board">
                {% if player.color == 'white' %}
                    {% for key, column in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'] %}
                        <div class="one-column">
                            {% for line in 8..1 %}
                                {% if key is even %}
                                    <div id="{{ column ~ line }}" class="chess-table {{ line is even ? 'case-white' : 'case-black' }}"></div>
                                {% else %}
                                    <div id="{{ column ~ line }}" class="chess-table {{ line is even ? 'case-black' : 'case-white' }}"></div>
                                {% endif %}
                            {% endfor %}
                            <div class="chess-column-letter"><span>{{ column }}</span></div>
                        </div>
                    {% endfor %}
                    <div class="one-column">
                        {% for line in 8..1 %}
                            <div class="chess-line-number"><span>{{ line }}</span></div>
                        {% endfor %}
                    </div>
                {% else %}
                    {% for key, column in ['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a'] %}
                        <div class="one-column">
                            {% for line in 1..8 %}
                                {% if key is even %}
                                    <div id="{{ column ~ line }}" class="chess-table {{ line is even ? 'case-white' : 'case-black' }}"></div>
                                {% else %}
                                    <div id="{{ column ~ line }}" class="chess-table {{ line is even ? 'case-black' : 'case-white' }}"></div>
                                {% endif %}
                            {% endfor %}
                            <div class="chess-column-letter"><span>{{ column }}</span></div>
                        </div>
                    {% endfor %}
                    <div class="one-column">
                        {% for line in 1..8 %}
                            <div class="chess-line-number"><span>{{ line }}</span></div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="col-lg-3 col-md-12 col-sm-12">
            <div>
                <span id="timer-opponent"></span>
            </div>
            <div>
                <span id="timer-opponent"></span>
            </div>
            <div>
                Statut de connexion : <span class="opponent-connect"></span>
            </div>
            <div class="history">
                <div class="row text-center">
                    <div class="col-3 btn history-button" id="history-start"><i class="bi bi-chevron-double-left"></i></div>
                    <div class="col-3 btn history-button" id="history-backward"><i class="bi bi-chevron-left"></i></div>
                    <div class="col-3 btn history-button" id="history-forward"><i class="bi bi-chevron-right"></i></div>
                    <div class="col-3 btn history-button" id="history-end"><i class="bi bi-chevron-double-right"></i></div>
                </div>

                <div id="playerturn-start" class="{{ game.status != 'begining' ? 'd-none' }}">
                   <p>
                        {% if player.color == 'w' or player.color == 'white' %}
                            Vous jouez avec les blancs.<br>
                            C'est votre tour !
                        {% else %}
                            Vous jouez avec les noirs.
                        {% endif %}
                    </p>
                </div>

                <div class="history-section">
                    {% for moveNumber, oneMove in arrMovesForHtml %}
                        <div class="row move-{{ moveNumber }} text-center">
                            <div class="col-4">{{ moveNumber }}</div>
                            <div id="move-san-w-{{ moveNumber }}" class="col-4 one-move-san {{ loop.last and oneMove.san_black is not defined ? 'last-history-move' }}">{{ oneMove.san_white is defined ? oneMove.san_white }}</div>
                            <div id="move-san-b-{{ moveNumber }}" class="col-4 one-move-san {{ loop.last and oneMove.san_black is defined ? 'last-history-move' }}">{{ oneMove.san_black is defined ? oneMove.san_black }}</div>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div>
                Statut de connexion : <span class="player-connect">OK</span>
            </div>
            <div>
                <span id="timer-player"></span>
            </div>
        </div>
    </div>

    <div class="modal fade" id="promotion-modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <button class="button" id="q">reine</button>
                    <button class="button" id="r">tour</button>
                    <button class="button" id="b">fou</button>
                    <button class="button" id="n">cavalier</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}